### ISSUE TITLE
Scale seems incorrect for timing distributions

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#1231] opened 2021-03-08 17:00 UTC
See Fenix metric `perf_startup_application_on_create`. The scale should not be so large causing the plots to be confined to smaller vertical space.

**Comment by rafrombrc** [comment] 2021-03-29 22:20
example: https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_app_on_create_to_megazord_init/explore?ping_type=*&timeHorizon=WEEK

**Comment by mcomella** [comment] 2022-09-14 21:14
I noticed an odd behavior: the scale is correct when an even number of percentiles is selected but is broken when an odd number is selected (the latter which is the default). It doesn't seem to matter which percentiles are selected: e.g. adding one of 0.1% or 99.9% fixes the scale. Here's a sample:
- [default](https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_cold_main_app_to_first_frame/explore?aggType=avg&currentPage=1&timeHorizon=ALL)

![image](https://user-images.githubusercontent.com/759372/190263159-30a0e8cf-3c84-411a-9b2c-f78da45dfca0.png)

- [0.1% added](https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_cold_main_app_to_first_frame/explore?aggType=avg&currentPage=1&timeHorizon=ALL&visiblePercentiles=%5B95%2C75%2C50%2C25%2C5%2C0.1%5D)

![image](https://user-images.githubusercontent.com/759372/190263213-2b3eb154-93c2-4b54-86a9-cbb9750b7944.png)

- [99.9% added](https://glam.telemetry.mozilla.org/fenix/probe/perf_startup_cold_main_app_to_first_frame/explore?aggType=avg&currentPage=1&timeHorizon=ALL&visiblePercentiles=%5B99.9%2C95%2C75%2C50%2C25%2C5%5D)
(similar to 0.1% so omitting image)

Thus, **workaround:** select an even number of percentiles to make the scale usable.

The way this bug manifests makes me think there's a logic error in the class of errors similar to taking the number of items and dividing by 2 but not managing the float correctly or having code to take a median that doesn't correctly handle an odd number of items.

**Comment by mcomella** [comment] 2022-09-14 21:29
> the scale is correct when an even number of percentiles is selected but is broken when an odd number is selected (the latter which is the default).

**Correction:** the scale is only incorrect if you use 5 selected percentiles (i.e. the default): any other number has a desirable behavior.

I suspect this line, which returns early from additional yDomain calculations if we have 5 visible percentiles, may be the root cause:

https://github.com/mozilla/glam/blob/877daf4ababa56c6e984654bb9f9fe6e758696bc/src/components/explore/AggregationsOverTimeGraph.svelte#L203

**Comment by edugfilho** [comment] 2023-12-21 22:04
The issue no longer exists. It was probably fixed in https://github.com/mozilla/glam/pull/1379

**Closed as completed by edugfilho** 2023-12-21 22:04 UTC
Labels: frontend
