### ISSUE TITLE
After auth, redirect to requested URL

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#542] opened 2020-05-26 17:42 UTC
I clicked a glam link from slack and was required to authenticate. After authentication I was redirected to the home page instead of the link that was clicked.

**Comment by mitchell-frost** [comment] 2020-05-27 18:43
I am new to mozilla. Can I work on this?

**Comment by openjck** [comment] 2020-05-27 21:00
Hi Bhawna,

This may not be the best project to get started with due to its complexity and reliance on private data. I recommend taking a look at [codetribute.mozilla.org](https://codetribute.mozilla.org/) which lists some projects that might be a better fit.

If you are committed to helping out on this project, I think anything labelled [cleanup](https://github.com/mozilla/glam/issues?q=is%3Aissue+is%3Aopen+label%3A%22cleanup%22+) would be a good place to start. Some of those tasks are already in progress, some aren't. Please comment in one of those issues if you're interested in helping out. 😃

**Comment by openjck** [comment] 2020-05-30 04:56
Note to self: Since I'm going to be testing auth pretty extensively while fixing this, I might as well update auth0-spa-js first (#543).

**Comment by mitchell-frost** [comment] 2020-06-01 06:14
@openjck  Thanks!

**Comment by openjck** [comment] 2020-06-24 03:28
@robhudson I know it's been a while, but do you happen to remember what the link was? I'm not able to reproduce this right now.

**Comment by robhudson** [comment] 2020-06-24 17:17
I just cleared my cookies, then hit a probe URL, saw the auth redirect, and was sent back to the probe URL. So yeah, I'm not seeing this any longer. I wonder if you have to do a full auth0 log in if fails to redirect to the original URL, but not sure how to test that.

**Comment by openjck** [comment] 2020-06-24 17:52
That could be. It could also be that stage was stale at the time. Let's close it for now but keep an eye on it. Thank you for reporting.

**Closed as completed by openjck** 2020-06-24 17:52 UTC
