### ISSUE TITLE
 addons_has_enabled_addons on Fenix does not work

### ISSUE THREAD

**Issue by wlach** [mozilla/glam#1221] opened 2021-03-01 14:47 UTC
E.g. https://glam.telemetry.mozilla.org/fenix/probe/addons_has_enabled_addons/explore?activeBuckets=%5B%22never%22%2C%22always%22%2C%22sometimes%22%5D&ref=2021022617

Seeing these errors in the console and it doesn't work:

![Screen Shot 2021-03-01 at 9 46 58 AM](https://user-images.githubusercontent.com/20569/109513413-12ca2f00-7a73-11eb-82b7-38ed0596a486.png)

/cc @robhudson

**Comment by Iinh** [comment] 2021-08-18 18:34
duplicate of #1524

**Closed as completed by Iinh** 2021-08-18 18:34 UTC
