### ISSUE TITLE
visual improvement: let's just label these axes, shall we?

### ISSUE THREAD

**Issue by hamilton** [mozilla/glam#302] opened 2020-03-11 14:59 UTC
People will be invariably confused by the lack of labels on the axes. So we should add them. It's the right thing to do.

**Comment by KaustubhKumar05** [comment] 2020-07-07 04:51
Hello! I would like to work on this issue. Could you please elaborate?

**Comment by rafrombrc** [comment] 2021-09-29 18:31
We can do this for Glean probes, but I don't know if there's a way to reliably get Y axis units for desktop telemetry probes.

**Comment by edugfilho** [comment] 2023-12-21 21:36
Closing this as a duplicate of https://github.com/mozilla/glam/issues/638. Keeping that one because it has more context

**Closed as not planned by edugfilho** 2023-12-21 21:36 UTC
Labels: enhancement, frontend
