### ISSUE TITLE
Clicking on table view seems to lose the filter selection

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glam#1552] opened 2021-09-01 18:56 UTC
Clicking from 'explore' view to 'table' view reset my channel selector from Release to Nightly, which is unexpected, we should try to persist those selections when you change views.

**Comment by Iinh** [comment] 2021-09-08 18:07
closing because we were not able to reproduce this bug.

**Closed as completed by Iinh** 2021-09-08 18:07 UTC
